# Generated by Django 5.1 on 2024-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='activity',
            field=models.CharField(default=18, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='person',
            name='experience',
            field=models.CharField(default=18, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='honors',
            field=models.CharField(default=18, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='person',
            name='objective',
            field=models.CharField(default=18, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='qualification',
            field=models.CharField(default=18, max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='service',
            field=models.CharField(default=18, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.CharField(default=18, max_length=30),
        ),
    ]
