# Generated by Django 5.1 on 2024-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_honors_person_honor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='activity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='honor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='objective',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='qualification',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='service',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.CharField(max_length=30),
        ),
    ]
