# Generated by Django 5.1 on 2024-09-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_person_activity_alter_person_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='objective',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='qualification',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.TextField(max_length=30),
        ),
    ]
